//! Build script: generates board config from YAML + auto-selects MCU feature.
//!
//! Usage: BOARD=boards/gen_64k_g071.yaml cargo build
//! If BOARD is not set, uses a default based on the active feature flag.

use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct BoardYaml {
    name: String,
    mcu: String,
    dead_time: u8,
    #[serde(default = "default_voltage_divider")]
    voltage_divider: u16,
    #[serde(default = "default_mv_per_amp")]
    millivolt_per_amp: u16,
    #[serde(default)]
    current_offset: i16,
    #[serde(default = "default_current_ch")]
    current_adc_channel: u8,
    #[serde(default = "default_voltage_ch")]
    voltage_adc_channel: u8,
    #[serde(default = "default_stall")]
    stall_protect_interval: u16,
    #[serde(default = "default_bemf")]
    min_bemf_counts: u8,
    #[serde(default)]
    has_led: bool,
    #[serde(default)]
    led_pin: Option<u8>,
    #[serde(default)]
    use_ntc: bool,
    #[serde(default)]
    inverted_input: bool,
    #[serde(default = "default_kv")]
    kv_divider: u8,
    #[serde(default)]
    startup_boost: bool,
    #[serde(default)]
    voltage_based_ramp: bool,
    #[serde(default)]
    pulse_output: bool,
    #[serde(default)]
    dual_adc: bool,
    #[serde(default)]
    bridge_enable: bool,
    #[serde(default)]
    custom_led: bool,
}

fn default_voltage_divider() -> u16 {
    110
}
fn default_mv_per_amp() -> u16 {
    20
}
fn default_current_ch() -> u8 {
    4
}
fn default_voltage_ch() -> u8 {
    6
}
fn default_stall() -> u16 {
    6500
}
fn default_bemf() -> u8 {
    2
}
fn default_kv() -> u8 {
    1
}

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("board_config.rs");

    // Determine board YAML path
    let board_path = if let Ok(path) = env::var("BOARD") {
        println!("cargo:rerun-if-env-changed=BOARD");
        path
    } else {
        // Default based on active feature
        let default = if cfg!(feature = "stm32g071") {
            "boards/gen_64k_g071.yaml"
        } else if cfg!(feature = "stm32f051") {
            "boards/siskin_f051.yaml"
        } else if cfg!(feature = "stm32l431") {
            "boards/neutron_l431.yaml"
        } else if cfg!(feature = "stm32g431") {
            "boards/protondrive_g431.yaml"
        } else {
            "boards/gen_64k_g071.yaml"
        };
        default.to_string()
    };

    println!("cargo:rerun-if-changed={}", board_path);

    let yaml = fs::read_to_string(&board_path)
        .unwrap_or_else(|e| panic!("Failed to read board config '{}': {}", board_path, e));
    let board: BoardYaml = serde_yaml::from_str(&yaml)
        .unwrap_or_else(|e| panic!("Failed to parse board config '{}': {}", board_path, e));

    // Generate the board config Rust code
    let led_pin = match board.led_pin {
        Some(p) => format!("Some({})", p),
        None => "None".to_string(),
    };

    let code = format!(
        r#"// Auto-generated by build.rs from {board_path}
// Do not edit manually.

/// Board configuration generated from YAML.
pub const BOARD: rm32::board::BoardConfig = rm32::board::BoardConfig {{
    name: "{name}",
    dead_time: {dead_time},
    voltage_divider: {voltage_divider},
    millivolt_per_amp: {millivolt_per_amp},
    current_offset: {current_offset},
    current_adc_channel: {current_adc_channel},
    voltage_adc_channel: {voltage_adc_channel},
    stall_protect_interval: {stall_protect_interval},
    min_bemf_counts: {min_bemf_counts},
    has_led: {has_led},
    led_pin: {led_pin},
    use_ntc: {use_ntc},
    inverted_input: {inverted_input},
    kv_divider: {kv_divider},
    startup_boost: {startup_boost},
    voltage_based_ramp: {voltage_based_ramp},
    pulse_output: {pulse_output},
    dual_adc: {dual_adc},
    bridge_enable: {bridge_enable},
    custom_led: {custom_led},
}};
"#,
        board_path = board_path,
        name = board.name,
        dead_time = board.dead_time,
        voltage_divider = board.voltage_divider,
        millivolt_per_amp = board.millivolt_per_amp,
        current_offset = board.current_offset,
        current_adc_channel = board.current_adc_channel,
        voltage_adc_channel = board.voltage_adc_channel,
        stall_protect_interval = board.stall_protect_interval,
        min_bemf_counts = board.min_bemf_counts,
        has_led = board.has_led,
        led_pin = led_pin,
        use_ntc = board.use_ntc,
        inverted_input = board.inverted_input,
        kv_divider = board.kv_divider,
        startup_boost = board.startup_boost,
        voltage_based_ramp = board.voltage_based_ramp,
        pulse_output = board.pulse_output,
        dual_adc = board.dual_adc,
        bridge_enable = board.bridge_enable,
        custom_led = board.custom_led,
    );

    fs::write(&dest, code).unwrap();

    // Auto-set MCU feature based on YAML (informational — the feature must still
    // be passed via Cargo, but this validates consistency)
    let expected_feature = format!("stm32{}", board.mcu.replace("stm32", ""));
    println!("cargo:rustc-env=BOARD_MCU={}", board.mcu);
    println!("cargo:rustc-env=BOARD_NAME={}", board.name);
}
